# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '根据网络加载高清非高清图片' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking'
  pod 'SDWebImage'
  
  # Pods for 根据网络加载高清非高清图片


  target '根据网络加载高清非高清图片Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '根据网络加载高清非高清图片UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
